import {mkdir,readdir,readFile,writeFile} from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT=join(dirname(fileURLToPath(import.meta.url)),'..');
const OUT=join(ROOT,'topics');
const defs=[
  {id:'chatgpt',name:'ChatGPT',label:'المساعد الأشهر من الأساسيات إلى الاستخدام المتقدم',desc:'أدلة عربية عملية تساعدك على فهم ChatGPT، كتابة موجّهات أفضل، تحليل الملفات، وبناء مساعدين مخصّصين من دون تضخيم لقدراته.',promise:'ابدأ بالأساسيات، ثم انتقل إلى التطبيقات التي تخدم عملك فعلاً.'},
  {id:'claude',name:'Claude',label:'كتابة أعمق وسياق أطول وسير عمل أوضح',desc:'مسار يشرح أين يتفوّق Claude، وكيف تستخدم المشاريع والتعليمات المخصّصة والمستندات الطويلة بقرار عملي لا بمقارنة سطحية.',promise:'اختر Claude عندما تكون جودة السياق والكتابة أهم من كثرة الميزات.'},
  {id:'gemini',name:'Gemini',label:'قوة منظومة جوجل في مساعد متعدد الوسائط',desc:'أدلة لفهم Gemini واستخدامه مع النصوص والصور والعمل اليومي، مع مقارنة واضحة لما يقدمه فعلاً داخل منظومة جوجل.',promise:'استخدم التكامل مع أدواتك الحالية كمعيار، لا اسم النموذج وحده.'},
  {id:'ai-tools',name:'أدوات الذكاء الاصطناعي',label:'اختيارات عملية بلا قوائم مزدحمة',desc:'أدوات للأتمتة والكتابة والصوت والفيديو والبحث وإدارة العمل، مصنّفة بحسب المهمة مع توضيح المجاني والمدفوع وحدود كل خيار.',promise:'ابدأ بالمهمة التي تتكرر لديك، ثم اختر أداة واحدة وأتقنها.'},
  {id:'ai-business',name:'الربح والأعمال',label:'من استخدام الأدوات إلى بناء قيمة تُباع',desc:'مسارات واقعية لبناء خدمات ومنتجات رقمية ومشروعات صغيرة بالذكاء الاصطناعي، بعيداً عن وعود الدخل السريع والوصفات المنسوخة.',promise:'القيمة أولاً، ثم النظام، ثم الأتمتة؛ بهذا الترتيب.'},
  {id:'learn-ai',name:'تعلّم الذكاء الاصطناعي',label:'أساس متين وخارطة تطبيق واضحة',desc:'من المفاهيم الأساسية والأمان والخصوصية إلى خارطة التعلّم وسوق العمل، بلغة عربية تشرح الفكرة ثم تنقلك إلى خطوة عملية.',promise:'افهم الأساس مرة واحدة، وستصبح الأدوات الجديدة أسهل كثيراً.'}
];

function decode(value=''){return value.replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#039;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function plain(value=''){return decode(value.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());}
function escapeHtml(value=''){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function schema(html,type){for(const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){try{const data=JSON.parse(m[1]);if(data['@type']===type)return data;}catch(e){}}return {};}
function groupFor(section=''){
  if(/ChatGPT/i.test(section))return 'chatgpt';
  if(/Claude/i.test(section))return 'claude';
  if(/Gemini/i.test(section))return 'gemini';
  if(/ربح|دخل|مشروع|اقتصاد|تسويق|أعمال|ريادة/.test(section))return 'ai-business';
  if(/تعلم|تعلّم|تعليم|أمان|خصوصية|مستقبل/.test(section))return 'learn-ai';
  return 'ai-tools';
}

const files=(await readdir(join(ROOT,'articles'))).filter(x=>x.endsWith('.html'));
const articles=[];
for(const file of files){
  const html=await readFile(join(ROOT,'articles',file),'utf8');
  const data=schema(html,'Article');
  const title=plain(html.match(/<h1 class="ah-title">([\s\S]*?)<\/h1>/)?.[1]||data.headline||'');
  const section=plain(html.match(/<span class="ah-cat">([\s\S]*?)<\/span>/)?.[1]||data.articleSection||'مقالات');
  const description=plain(html.match(/<meta name="description" content="([^"]+)">/)?.[1]||data.description||'');
  const words=Number(html.match(/data-word-count="(\d+)"/)?.[1]||0);
  articles.push({file,stem:file.replace(/\.html$/,''),title,section,description,words,minutes:Math.max(1,Math.ceil(words/155)),published:data.datePublished||'',group:groupFor(section)});
}
articles.sort((a,b)=>b.published.localeCompare(a.published)||b.file.localeCompare(a.file,undefined,{numeric:true}));
await mkdir(OUT,{recursive:true});

function nav(){return `<header><div class="container nav"><a class="logo" href="../index.html" aria-label="نَوَاة - الصفحة الرئيسية"><svg width="34" height="34" viewBox="0 0 34 34" fill="none" aria-hidden="true"><circle cx="17" cy="17" r="6" fill="#B8573D"/><circle cx="17" cy="17" r="13" stroke="#251C18" stroke-width="2" stroke-dasharray="4 5"/><circle cx="29" cy="11" r="3" fill="#7A8061"/></svg>نَوَاة</a><nav class="nav-links" id="navLinks" aria-label="التنقل الرئيسي"><a href="../archive.html" class="navlink active">المقالات</a><a href="../news.html" class="navlink">الأخبار</a><a href="../store.html" class="navlink nav-store-link">المتجر</a><a href="../tools.html" class="navlink">الأدوات</a><a href="../generators.html" class="navlink">المولّدات</a><a href="../ats-checker.html" class="navlink">فاحص السيرة</a><a href="../glossary.html" class="navlink">المعجم</a></nav><div class="search-box"><input type="search" id="siteSearch" placeholder="ابحث في الموقع..." aria-label="بحث في الموقع" autocomplete="off"><div class="search-results" id="searchResults" role="listbox"></div></div><button class="nav-toggle" id="navToggle" aria-label="القائمة" aria-expanded="false" aria-controls="navLinks"><span></span><span></span><span></span></button><button class="theme-btn" id="themeBtn" aria-label="تبديل الوضع الليلي" title="الوضع الليلي">☾</button><button class="cart-btn" id="cartBtn" aria-label="فتح سلة المشتريات">السلة · <span class="cart-count" id="cartCount">0</span></button></div></header>`;}
function footer(){return `<footer><div class="container"><div class="footer-grid"><div><h4>نَوَاة</h4><p style="font-size:.9rem">مدونة ومتجر عربي متخصص في الذكاء الاصطناعي. محتوى معمّق، ومنتجات رقمية تنقلك من الفهم إلى الإتقان.</p></div><div><h4>المحتوى</h4><a href="../archive.html">المقالات</a><a href="chatgpt.html">ChatGPT</a><a href="claude.html">Claude</a><a href="gemini.html">Gemini</a></div><div><h4>المسارات</h4><a href="ai-tools.html">أدوات الذكاء الاصطناعي</a><a href="ai-business.html">الربح والأعمال</a><a href="learn-ai.html">تعلّم الذكاء الاصطناعي</a><a href="../store.html">المتجر الرقمي</a></div><div><h4>الموقع</h4><a href="../about.html">من نحن</a><a href="../editorial.html">منهجية التحرير</a><a href="../contact.html">تواصل معنا</a><a href="../privacy.html">الخصوصية</a></div></div><div class="footer-bottom"><span>© 2026 نَوَاة. جميع الحقوق محفوظة.</span><span><a href="../privacy.html" style="display:inline">سياسة الخصوصية</a> · <a href="../terms.html" style="display:inline">شروط الاستخدام</a> · <a href="../refund.html" style="display:inline">سياسة الاسترجاع</a></span></div></div></footer><div class="drawer" id="cartDrawer" role="dialog" aria-modal="true" aria-label="سلة المشتريات" aria-hidden="true"><div class="drawer-panel"><h3>سلة المشتريات <button class="close-x" id="cartClose" aria-label="إغلاق السلة">✕</button></h3><div id="cartItems"></div><div class="cart-total" id="cartFooter" style="display:none"><div class="row"><span>الإجمالي</span><span id="cartTotal">0 ر.س</span></div><button class="btn btn-primary" style="width:100%;justify-content:center" id="checkoutBtn">مراجعة المنتجات والدفع</button><p class="secure-note">ستراجع المنتجات وروابط الدفع بوضوح قبل الانتقال إلى مزود الدفع.</p></div></div></div><div class="toast" id="toast" role="status" aria-live="polite"></div>`;}

for(const def of defs){
  const list=articles.filter(a=>a.group===def.id);
  const roadmap=list.slice(0,3).map((a,i)=>`<a href="../articles/${a.file}"><span>${String(i+1).padStart(2,'0')}</span><small>${escapeHtml(a.section)}</small><strong>${escapeHtml(a.title)}</strong><i>${a.minutes.toLocaleString('ar-SA')} دقيقة ←</i></a>`).join('');
  const cards=list.map(a=>`<article class="topic-card"><a class="topic-card-cover" href="../articles/${a.file}"><img src="../assets/covers/${a.stem}.svg?v=41" width="1200" height="630" loading="lazy" decoding="async" alt="غلاف: ${escapeHtml(a.title)}"></a><div><span>${escapeHtml(a.section)}</span><h2><a href="../articles/${a.file}">${escapeHtml(a.title)}</a></h2><p>${escapeHtml(a.description)}</p><div class="topic-card-meta"><small>${a.minutes.toLocaleString('ar-SA')} دقيقة · ${a.words.toLocaleString('ar-SA')} كلمة</small><a href="../articles/${a.file}">اقرأ ←</a></div></div></article>`).join('');
  const itemList={"@context":"https://schema.org","@type":"CollectionPage","name":def.name,"url":`https://nawahlabs.com/topics/${def.id}.html`,"inLanguage":"ar","mainEntity":{"@type":"ItemList","numberOfItems":list.length,"itemListElement":list.map((a,i)=>({"@type":"ListItem","position":i+1,"url":`https://nawahlabs.com/articles/${a.file}`,"name":a.title}))}};
  const html=`<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${escapeHtml(def.name)} | أدلة نَوَاة</title><meta name="description" content="${escapeHtml(def.desc)}"><meta name="robots" content="index, follow"><link rel="canonical" href="https://nawahlabs.com/topics/${def.id}.html"><meta name="theme-color" content="#2A201B"><meta property="og:type" content="website"><meta property="og:locale" content="ar_SA"><meta property="og:title" content="${escapeHtml(def.name)} | أدلة نَوَاة"><meta property="og:description" content="${escapeHtml(def.desc)}"><meta property="og:url" content="https://nawahlabs.com/topics/${def.id}.html"><meta property="og:site_name" content="نَوَاة"><meta property="og:image" content="https://nawahlabs.com/assets/og-nawah.png"><meta name="twitter:card" content="summary_large_image"><link rel="manifest" href="../manifest.json"><link rel="icon" href="../assets/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="../assets/icon-192.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Alexandria:wght@400;500;600;700;800&family=IBM+Plex+Sans+Arabic:wght@300;400;500;600;700&family=Noto+Naskh+Arabic:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/style.css?v=41"><script type="application/ld+json">${JSON.stringify(itemList)}</script></head><body class="topic-page topic-${def.id}"><a class="skip-link" href="#main-content">تجاوز إلى المحتوى</a><div id="progress"></div>${nav()}<main id="main-content"><section class="topic-hero"><div class="container"><nav class="breadcrumb"><a href="../index.html">الرئيسية</a> ← <a href="../archive.html">المقالات</a> ← ${escapeHtml(def.name)}</nav><span>NAWAH / TOPIC FILE</span><h1>${escapeHtml(def.name)}</h1><p>${escapeHtml(def.desc)}</p><div class="topic-hero-foot"><strong>${list.length.toLocaleString('ar-SA')} مقالات معمّقة</strong><em>${escapeHtml(def.label)}</em></div></div></section><section class="topic-roadmap"><div class="container"><header><span>مسار البداية</span><h2>ثلاث قراءات مرتبة لتبدأ بوضوح.</h2><p>${escapeHtml(def.promise)}</p></header><div>${roadmap}</div></div></section><section class="topic-library"><div class="container"><header><span>كل الملفات</span><h2>${escapeHtml(def.name)} في نَوَاة</h2><a href="../archive.html">العودة إلى الأرشيف الكامل ←</a></header><div class="topic-grid">${cards}</div></div></section></main>${footer()}<script>window.NAWAH_ROOT="../";</script><script src="../assets/data.js?v=41"></script><script src="../assets/consent.js?v=41" defer></script><script src="../assets/main.js?v=41" defer></script></body></html>\n`;
  await writeFile(join(OUT,`${def.id}.html`),html.replaceAll('.svg?v=41','.png?v=44').replaceAll('?v=41','?v=44'),'utf8');
}
console.log(`Built ${defs.length} topic pages covering ${articles.length} articles.`);
